import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

/**
 * Project files generated by `wpdev init` for Claude Code (SPEC 3.7, section 6).
 * Every function merges with existing content and is idempotent.
 */

async function readText(file: string): Promise<string | undefined> {
  return existsSync(file) ? readFile(file, 'utf8') : undefined;
}

/** `.gitattributes` with `* -text`: git keeps files byte for byte (no CRLF conversion). */
export async function ensureGitattributes(dir: string): Promise<boolean> {
  const file = path.join(dir, '.gitattributes');
  const current = (await readText(file)) ?? '';
  if (current.split(/\r?\n/).some((l) => /^\*\s+-text\s*$/.test(l.trim()))) {
    return false;
  }
  const sep = current === '' || current.endsWith('\n') ? '' : '\n';
  await writeFile(file, `${current}${sep}# wpdev: keep files byte for byte, identical to the server\n* -text\n`, 'utf8');
  return true;
}

function wpdevArgs(insecureLocal: boolean, ...rest: string[]): string[] {
  return insecureLocal ? ['--insecure-local', ...rest] : rest;
}

type JsonObject = Record<string, unknown>;

async function readJsonObject(file: string): Promise<JsonObject> {
  const text = await readText(file);
  if (text === undefined || text.trim() === '') return {};
  const data = JSON.parse(text) as unknown;
  if (!data || typeof data !== 'object' || Array.isArray(data)) {
    throw new Error(`${path.basename(file)} non contiene un oggetto JSON`);
  }
  return data as JsonObject;
}

function asObject(value: unknown): JsonObject {
  return value && typeof value === 'object' && !Array.isArray(value) ? (value as JsonObject) : {};
}

/** Adds the Stop hook `wpdev deploy --hook` to `.claude/settings.json`, preserving other settings. */
export async function ensureStopHook(dir: string, insecureLocal: boolean): Promise<boolean> {
  const file = path.join(dir, '.claude', 'settings.json');
  const settings = await readJsonObject(file);
  const command = ['wpdev', ...wpdevArgs(insecureLocal, 'deploy', '--hook')].join(' ');
  const hooks = asObject(settings.hooks);
  const stop = Array.isArray(hooks.Stop) ? (hooks.Stop as unknown[]) : [];
  const present = stop.some((group) => {
    const inner = asObject(group).hooks;
    return Array.isArray(inner) && inner.some((h) => typeof asObject(h).command === 'string' && /\bwpdev\b.*\bdeploy\b.*--hook/.test(String(asObject(h).command)));
  });
  if (present) return false;
  stop.push({ hooks: [{ type: 'command', command, timeout: 300 }] });
  hooks.Stop = stop;
  settings.hooks = hooks;
  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, `${JSON.stringify(settings, null, 2)}\n`, 'utf8');
  return true;
}

/** Registers the `wpdev` MCP server in `.mcp.json` (project scope). */
export async function ensureMcpServer(dir: string, insecureLocal: boolean): Promise<boolean> {
  const file = path.join(dir, '.mcp.json');
  const config = await readJsonObject(file);
  const servers = asObject(config.mcpServers);
  if (servers.wpdev) return false;
  servers.wpdev = { command: 'wpdev', args: wpdevArgs(insecureLocal, 'mcp') };
  config.mcpServers = servers;
  await writeFile(file, `${JSON.stringify(config, null, 2)}\n`, 'utf8');
  return true;
}

export interface ClaudeMdInput {
  name: string;
  url: string;
  writable: readonly string[];
}

/** CLAUDE.md for the site project, from the template of SPEC section 6. */
export function renderClaudeMd(input: ClaudeMdInput): string {
  const base = (prefix: string): string[] =>
    input.writable.filter((w) => w.toLowerCase().startsWith(prefix)).map((w) => w.slice(prefix.length).split('/')[0] ?? w);
  const themes = base('wp-content/themes/');
  const plugins = base('wp-content/plugins/');
  const list = input.writable.map((w) => `\`${w}\``).join(', ') || '(nessuna: configura `writable` in wpdev.json)';
  return `# Sito: ${input.name} — ${input.url}

## Come lavori su questo sito
- Puoi modificare SOLO i file in: ${list}. Le modifiche vengono pubblicate
  automaticamente alla fine di ogni turno (hook), con health check e rollback.
- Per leggere qualsiasi altro file del sito (core, plugin, tema padre) usa gli strumenti
  MCP \`site_list\`, \`site_read\`, \`site_grep\`. Preferisci \`site_grep\` per trovare hook,
  filtri e classi; poi leggi solo le righe che servono con \`site_read\`.
- Non cercare di scrivere fuori dalle cartelle consentite: il server lo rifiuta.
- Se il deploy fallisce, leggi gli errori riportati, controlla \`site_log\` e correggi.
- Dopo modifiche visibili, verifica la pagina nel browser (Chrome).
- Contenuti e pagine Elementor si gestiscono con l'MCP del sito (WSP), non via file.

## Convenzioni
- Child theme: ${themes.join(', ') || '<nome>'}. Plugin custom: ${plugins.join(', ') || '<nome>'}, prefisso funzioni \`<prefisso>_\`.
- Page builder: Elementor.
`;
}

/** Writes CLAUDE.md, or CLAUDE.wpdev.md when a CLAUDE.md already exists (never overwritten). */
export async function writeClaudeMd(dir: string, input: ClaudeMdInput): Promise<string> {
  const target = existsSync(path.join(dir, 'CLAUDE.md')) ? 'CLAUDE.wpdev.md' : 'CLAUDE.md';
  await writeFile(path.join(dir, target), renderClaudeMd(input), 'utf8');
  return target;
}
